### ISSUE TITLE
Fatal Declaration

### ISSUE THREAD

**Issue by ggomezz** [TheFixerDevelopment/SkyblockPE#1]
Fatal error: Declaration of SkyBlock\generator\generators\BasicIsland::generateChunk($chunkX, $chunkZ) must be compatible with pocketmine\level\generator\Generator::generateChunk(int $chunkX, int $chunkZ) in phar:///home/shop/plugins/SkyBlockPE_v0.2.0.phar/src/SkyBlock/generator/generators/BasicIsland.php on line 12
[14:37:09] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[14:37:09] [Server thread/EMERGENCY]: Please upload the "/home/shop/crashdumps/Mon_Aug_7-14.37.09-UTC_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

I am running my server on 3.0.0-ALPHA7 with a Linux VPS
This error occurred on startup using this .phar: https://github.com/TheFixerDevelopment/SkyblockPE/releases/tag/v0.2.0

**Comment by TheFixerDevelopment** [comment]
It works for me on GenisysPro. I'll see what I can do. Thanks for reporting.

**Comment by TheFixerDevelopment** [comment]
I believe this is due to the Pocketmine and Genisys code looking different. I'll try making a new branch for Pocketmine only. There can be other reasons, such as: 3.0.0-ALPHA7 is new, and can contain bugs, and crashes. If possible, may you try downgrading to 3.0.0-ALPHA6. Tell me if that works. Thanks.

**Comment by TheFixerDevelopment** [comment]
Okay, we've made a new branch for Pocketmine-ONLY. You can head over to This branch [Here](https://github.com/TheFixerDevelopment/SkyblockPE/tree/Pocketmine-ONLY)
We'll be developing more things-related to Pocketmine ONLY. Closing issue. If you need any more help or it still doesn't work, please open a new issue. Thanks.

**Comment by ggomezz** [comment]
Alright, thank you! I will try it out
