### ISSUE TITLE
Owner transfer 

### ISSUE THREAD

**Issue by nasiridrishi** [TheFixerDevelopment/SkyblockPE#3]
Please fix the owner transfer Command.. player loose island after trying the command /skyblocks transferowner or something.. non of them get it and main owner looses access to it

**Comment by TheFixerDevelopment** [comment]
Could you please be a bit more specific on the issue? Thanks.

**Comment by nasiridrishi** [comment]
ok I will try this plugin and report debug if there is any!

**Comment by TheFixerDevelopment** [comment]
Okay, thanks. :) Closing issue. If you have any issues regarding the server, please make/open a new issue.

**Comment by dresnite** [comment]
Please, report the issue in the original repo. @optimusprime338
https://github.com/GiantQuartz/SkyBlock
This project is again active in my repo, the latest stable version is available in the release section.

Thanks for keeping my project active while I was inactive, @TheFixerDevelopment !

**Comment by TheFixerDevelopment** [comment]
Anytime. I'll still keep going on with this project, as I'm doing some tests with it on my server. And making a skyblock server with it.

**Comment by nasiridrishi** [comment]
welcome back @GiantQuartz
