### ISSUE TITLE
1 world per island?

### ISSUE THREAD

**Issue by inxomnyaa** [TheFixerDevelopment/SkyblockPE#4]
is this the plugin where every island is an own world which will literally cause most performace issues ever or is it 1 world?

**Comment by TheFixerDevelopment** [comment]
It's 1 island per world. We're trying to fix issues such as that in the next future updates.

**Comment by TheFixerDevelopment** [comment]
Closing issue as it was solved.

**Comment by xXSirGamesXx** [comment]
The original plugin wasnt coded well thats probably why.
