### ISSUE TITLE
skyblock expel not working

### ISSUE THREAD

**Issue by nasiridrishi** [TheFixerDevelopment/SkyblockPE#5]
steps:- 
1. do /skyblock invite player  
2. player accepted
3. do /sb expel name
3. message came with sucessfully kicked 
4. player still can join skyblock and have full access
pmmp version:- latest
skyblockpe version:- latest(pocketmine only)
same happening with genesis and its version!

 kindely fix it ..
thanks

**Comment by TheFixerDevelopment** [comment]
Did you try the other branches? Like testing? As the one you used (Pocketmine ONLY) is outdated.
What version are you on? ALPHA7 or ALPHA6 of Pocketmine?

**Comment by nasiridrishi** [comment]
I using latest PMMP release and testing branch is not working on it . I will post error one sec

**Comment by nasiridrishi** [comment]
PMMP version:-  PocketMine-MP 1.6.2dev+poggit.1488
skyblock verion:- latest releas (testing branch)
 
updated errors  and tested that remove thing still not working!

**Comment by TheFixerDevelopment** [comment]
Are there any errors on console? If so, please give me the copy and paste errors so I can take a look. Thanks.

**Comment by xXSirGamesXx** [comment]
I think /sb expel only kicks the player anyways.

**Comment by TheFixerDevelopment** [comment]
I added a alias command, which is /is kick.

**Comment by nasiridrishi** [comment]
I was talking about /sb remove and there are no errors and one more thing island owner transfer dont work too! like if I did transfered  my island  ownership to someone else. both player loose there access on island ie. island is gon but still if they both do /sb join they go to that island..

**Comment by TheFixerDevelopment** [comment]
Thanks for reporting. I'll try getting it fixed. Closing issue. If you have any more issues, please make a new issue. Thanks.

**Comment by nasiridrishi** [comment]
Ur welcome and thanks for fixing
